default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: vagrant
  host: localhost

development:
  <<: *default
  database: AeroLP_Contenidos_production

production:
  <<: *default
  database: AeroLP_Contenidos_production
